name: Android - CI Tests

on:
  pull_request:
    branches: ["main", "develop"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Lint
        run: ./gradlew lintAnalyzeRelease
      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest
